#!/bin/sh
#
# Pre-commit hooks

# Grunt minify js
echo "Grunt running to create concatenated and minified javascript."
grunt mini
echo "File generated, adding to commit"
git add templates/includes/scripts/ncsulib-website.min.js
echo "File included in commit"

# create header.html
echo "Generating new head.html and header.html files"
php templates/includes/head.php > templates/includes/head.html
php templates/includes/header.php > templates/includes/header.html
echo "Files generated, adding to commit"
git add templates/includes/head.html
git add templates/includes/header.html
echo "File included in commit"